language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.txt"
  - "pip install pytest pytest-cov"
  - "pip install coveralls"
  - "pip install -e ."   # install package using setup.py in editable mode
script:
   - py.test --cov geobricks_processing --cov-report term-missing